```js
var p1 = new Promise(function(resolve, reject) {
  throw Error("sync error");
})
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  });
```

```js
var p1 = new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw Error("async error");
  });
})
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  });
```

```js
var p1 = new Promise(function(resolve, reject) {
  resolve();
}).then(res => {
  throw Error("sync error");
});
```

```js
var p1 = new Promise(function(resolve, reject) {
  reject(1);
}).catch(err => {
  console.log(err);
  return 2;
});

setTimeout(() => {
  p1.then(res => console.log(res));
}, 1000);
```

```js
var p1 = new Promise(function(resolve, reject) {
  resolve();
  setTimeout(() => {
    console.log(1);
  });
  console.log(2);
}).then(res => {
  console.log(3);
});
console.log(4);
```

```js
var p1 = new Promise(function(resolve, reject) {
  resolve(1);
})
  .then(res => {
    throw Error("sync error");
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  });
```

```js
var p1 = new Promise(function(resolve, reject) {
  resolve(1);
})
  .then(res => {
    throw Error("sync error");
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  });
```
